#!/bin/bash

spinner() {
  local STEPS=("${@:1:$# / 2}")
  local CMDS=("${@:$# / 2 + 1}")

  local FRAME=("⠋" "⠙" "⠹" "⠸" "⠼" "⠴" "⠦" "⠧" "⠇" "⠏")
  local FRAME_INTERVAL=0.1
  local step=0

  tput civis

  while [ "$step" -lt "${#CMDS[@]}" ]; do
    LOG_FILE=/tmp/gke_tunnel_output.log
    ${CMDS[$step]} > $LOG_FILE 2>&1 &
    pid=$!

    while ps -p $pid &>/dev/null; do
      echo -ne "\\r[   ] ${STEPS[$step]} "

      for k in "${!FRAME[@]}"; do
        echo -ne "\\r[ ${FRAME[k]} ]"
        sleep $FRAME_INTERVAL
      done
    done
    wait $pid
    status=$?
    output=$(cat $LOG_FILE)

    if [ $status -eq 0 ]; then
        echo -ne "\\r[ ✔ ] ${STEPS[$step]}\\n"
        rm -f $LOG_FILE
    else
        echo -ne "\\r[ X ] ${STEPS[$step]}\\n"
        echo -e "$output"
        rm -f $LOG_FILE
        tput cnorm
        exit 1
    fi

    step=$((step + 1))

  done
  tput cnorm
}

remove_zsh_aliases() {
  if [[ $OSTYPE == 'darwin'* ]]; then
    local SED_COMMAND="sed -i ''"
  else
    local SED_COMMAND="sed -i"
  fi
  $SED_COMMAND "s/'HTTPS_PROXY=localhost:8888 kubectl/'kubectl/g" ~/.config/zsh/aliases/kubectl_aliases.zsh  
  $SED_COMMAND "s/'HTTPS_PROXY=localhost:8888 helm/'helm/g" ~/.config/zsh/aliases/helm_aliases.zsh
}

disable_active_connection() {
  if nc -z 127.0.0.1 8888 > /dev/null 2>&1; then
    if pgrep -f '\-M \-S /tmp/sslsock' > /dev/null 2>&1; then
      ssh -S /tmp/sslsock -O exit gke-mgmt > /dev/null 2>&1
    fi
  else
    return 0
  fi
}

RC_FILE="$HOME/.$(basename "$SHELL")"rc

STEPS=(
  "Removing GKE-TUNNEL aliases from $(echo "$RC_FILE" | sed "s|"$HOME"|~|g") file"
  "Disabling active GKE-TUNNEL connections"
)

CMDS=(
  "remove_zsh_aliases"
  "disable_active_connection > /dev/null 2>&1"
)

spinner "${STEPS[@]}" "${CMDS[@]}"
echo "==============================================================="
echo Done!
echo "Please run 'source $(echo "$RC_FILE" | sed "s|"$HOME"|~|g")' to refresh aliases."
